#!/bin/bash
# postinst

mv /System/Library/LaunchDaemons/* Library/LaunchDaemons
mv /Library/LaunchDaemons/com.apple.CrashHousekeeping.plist /System/Library/LaunchDaemons
mv /Library/LaunchDaemons/com.apple.MobileFileIntegrity.plist /System/Library/LaunchDaemons
mv /Library/LaunchDaemons/com.apple.jetsamproperties.*.plist /System/Library/LaunchDaemons
mv /Library/LaunchDaemons/com.apple.mDNSResponder.plist /System/Library/LaunchDaemons

mv /Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist.backup
mv /Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist /System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist.backup

mv -v /usr/libexec/CrashHousekeeping usr/libexec/CrashHousekeeping.backup
ln -s /lyncis /usr/libexec/CrashHousekeeping

chmod 0777 /lyncis
chown 0:0 /lyncis
chmod 0755 /usr/libexec/CrashHousekeeping
chown 0:0 /usr/libexec/CrashHousekeeping
rm -rf /install.sh

if [[ ${CYDIA+@} ]]; then
    declare -a cydia
    cydia=($CYDIA)
    eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0